# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'LabQueue' do

pod 'Google/SignIn'
pod 'GoogleAPIClient/Gmail', '~> 1.0.2'
pod 'GTMOAuth2', '~> 1.1.0'
pod 'Firebase', '>= 2.5.1'
pod 'Alamofire', '~> 3.4'
pod 'AlamofireImage', '~> 2.0'
pod 'Cosmos', '~> 1.2'
pod 'SCLAlertView'


end

target 'LabQueueTests' do

end

target 'LabQueueUITests' do

end

